### ISSUE TITLE
Players don't respawn at their bases

### ISSUE THREAD

**Issue by saber00** [UserXXX/CuBoltScripts#2]
Capture the Flag is a great pvp game however it could be improved if the players respawned at their bases. Changing the players to hostile makes it impossible to know where they are and makes it very hard to go back to the original location. Also, even though I enabled pvp, I couldn't attack others unless if I started the capture the flag game. Sometimes flags just randomly drop even if the player didn't die.

**Comment by UserXXX** [comment]
All of the additions (including making players respawn at their bases) have been made and checked in. There is also a new stable version of CTF that contains all of the changes. You will need to update CuBolt in order to use it.
